blog/urls.py
from django.urls import path
from . import views #to import blog app's view file

#declaring app name to access each blog
app_name = 'blog'

urlpatterns = [
    #coming from the main url file the default path goes like 'example.com/blog'
    path('', views.all_blogs, name='all_blogs'),
    #the route takes in a integer as input and shows the blog associated with it as output
    path('<int:blog_id>/', views.detailed_blog, name='detailed_blog'),
]

personal_portfolio/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from portfolio import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name="home"),
    path('blog/', include('blog.urls')), #to pass on the request to url file in blog app (as it ensures cleaner code)
]

urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

blog/models.py
from django.db import models

# Create your models here.
class Blog(models.Model):
    blog_Title = models.CharField(max_length=150)
    blog_Description = models.TextField()
    blog_Date = models.DateField()

    #this shows the blog's actual title instead of default title in the admin dashboard
    def __str__(self):
        return self.blog_Title

portfolio/models.py
from django.db import models

class Project(models.Model):
    project_Title = models.CharField(max_length=100)
    project_Description = models.CharField(max_length=350)
    project_Image = models.ImageField(upload_to='portfolio/images')
    project_URL = models.URLField(blank=True) #blank attribute gives an option to the user to whether include a url or not

    #this shows the project's actual title instead of default title in the admin dashboard
    def __str__(self):
        return self.project_Title

blog/views.py
from django.shortcuts import render, get_object_or_404

#importing model Blog for accessing its db
from .models import Blog

# Create your views here.
def all_blogs(request):
    blogs = Blog.objects.order_by('-blog_Date')[:3] #this grabs all the objects from the db in Blog, orders them in recent date order and limits visibility of only 3 blogs at a time
    blogs_count = Blog.objects.count() #to have a count of total number of blogs
    return render(request, 'blog/all_blogs.html', {'blogs': blogs, 'blogs_count': blogs_count})


def detailed_blog(request, blog_id):
    blog = get_object_or_404(Blog, pk=blog_id) #Blog refers to the class created in the model and pk refers to primary key
    return render(request, 'blog/detailed_blog.html', {'blog': blog})

portfolio/views.py
from django.shortcuts import render

#importing model Project for accessing its db
from .models import Project

# Create your views here.
def home(request):
    projects = Project.objects.all() #this grabs all the objects from the db in Project
    return render(request, 'portfolio/home.html', {'projects': projects})

blog/templates/blog/all_blogs.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Blogs</title>
</head>
<body>
    <!-- Extending base styles -->
    {% extends 'portfolio/base_style.html' %}
    {% block content %}
    <h1 id="blog_title" class="text-center">Welcome to Blogs</h1>
    <br>
    <!-- It accesses a variable created in view file and pluralize ensures that correct form of plural is applied for the no. of blogs -->
    <h3 class="text-center">AJ has written {{ blogs_count }} blog{{ blogs_count|pluralize}}!</h3> 
    <!-- Django tempating language - for loop -->
    {% for x in blogs %}
    <br>
    <div class="row justify-content-center">
        <div class="col-md-10">
            <!-- Here blog:detailed_blog refers to the app name and the name of the url path and pk refers to the id of the blog -->
            <a href="{% url 'blog:detailed_blog' x.pk %}"><h3>{{ x.blog_Title }}</h3></a>
            <!-- truncatechars ensures that the description is limited to only 100 chars visibility and then ....-->
            <p>{{ x.blog_Description|truncatechars:100 }}</p>
            <p>{{ x.blog_Date|date:'M d, Y'|upper }}</p>
        </div>
    </div>
    {% endfor %}
    {% endblock %}
    <!-- Ending content block -->
</body>
</html>

blog/templates/blog/detailed_blog.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Blog</title>
</head>
<body>
    <!-- Extending base styles -->
    {% extends 'portfolio/base_style.html' %}
    {% block content %}
    <br>
    <h1 id="detailed_blog_title" class="text-center">{{ blog.blog_Title }}</h1>
    <p class="text-center text-muted"><i>{{ blog.blog_Date|date:'F jS Y'}}</i></p>
    <br>
    <!-- safe ensures that the description follows its html formatting-->
    <p class="justify-content-center">{{ blog.blog_Description|safe }}</p>
    {% endblock %}
    <!-- Ending content block -->
</body>
</html>

portfolio/templates/portfolio/base_style.html
<!-- This acts as a base styling code for all the webpages -->
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <!-- Bootstrap CSS -->
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
        {% load static %}
        <!-- Load Custom css -->
        <link rel="stylesheet" href="{% static 'portfolio/custom.css' %}">
        <!-- Logo on title bar -->
        <link rel="icon" type="image/png" href="{% static 'portfolio/logo.png' %}" sizes="32*32">
        <title></title>
    </head>
    <body>
        <!-- Navigation -->
        <nav id="topNav" class="navbar navbar-expand-md navbar-dark" style="background-color: #6ab04c;">
            <div class="container">
                <a class="navbar-brand" href="{% url 'home' %}">
                    <img src="{% static 'portfolio/portfolio_logo.jpg' %}" width="40" height="40" class="d-inline-block align-top" alt="Logo">
                    <!-- <span> A J</span> -->
                </a>
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'home' %}">A J</a>
                    </li>
                </ul>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                  <span class="navbar-toggler-icon"></span>
                </button>
            
                <div class="collapse navbar-collapse text-center" id="navbarNav">
                    <ul class="navbar-nav ml-auto">
                        <li class="nav-item">
                            <a class="nav-link" href="{% static 'portfolio/sample_resume.pdf' %}">Resume <span class="sr-only">(current)</span></a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'blog:all_blogs' %}">Blogs</a>
                        </li>
                        <!--
                        <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Dropdown
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <a class="dropdown-item" href="#">Action</a>
                            <a class="dropdown-item" href="#">Another action</a>
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item" href="#">Something else here</a>
                        </div>
                        -->
                    </ul>
                    <!-- <form class="form-inline my-2 my-lg-0">
                        <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
                        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
                    </form> -->
                </div>
            </div>
        </nav>
        
        <div class="container">
            <!-- Accepting main content from the webpages -->
            {% block content %}
            {% endblock %}
        </div>

        <!-- JS files -->
        <!-- Optional JavaScript -->
        <!-- jQuery first, then Popper.js, then Bootstrap JS -->
        <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
    </body>
</html>

portfolio/templates/portfolio/home.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">        
        <title>Personal Portfolio</title>
    </head>
    <body>
        <!-- Extending base styles -->
        {% extends 'portfolio/base_style.html' %}
        {% block content %}
        {% load static %}
        <!-- To include static files like images, pdf -->
        <div class="row justify-content-center my-3">
            <div class="col-5">
                <img class="img-fluid" src="{% static 'portfolio/profile_pic.jpg' %}">
            </div>
        </div>
        <div class="row justify-content-center mb-3">
            <div class="col-md-9 text-center">
                <h4 id="home_text">This is my portfolio</h1>
            </div>
        </div>
        <h2 class="mt-5">Portfolio</h2>
        <hr>
        <div class="row">
            <!-- Django templating language - for loop to iterate through projects var in views -->
            {% for x in projects %}
            <div class="col-lg-6 col-md-6"> 
                <!-- if condition -->
                {% if x.project_URL %}
                <a href="{{ x.project_URL }}">
                    <img src = "{{ x.project_Image.url }}" height="300px" width="500px" class="mb-2">
                </a>
                {% else %}
                <img src = "{{ x.project_Image.url }}" height="300px" width="500px" class="mb-2">
                {% endif %}
                <h4>{{ x.project_Title }}</h4>
                <h5>{{ x.project_Description }}</h5>
            </div>
            {% endfor %}
        </div>
        {% endblock %} 

        <!-- Ending content block -->
    </body>
</html>